import { escapeHtml as esc } from './coachCore.js?v=1';
const law12='https://www.theifab.com/laws/latest/fouls-and-misconduct/';
const law15='https://www.theifab.com/laws/latest/the-throw-in/';
export const REFEREE_LESSONS = [
    {title:['몸싸움: 어깨면 무조건 괜찮을까?','Contact: is shoulder contact always fair?'],question:['공을 다투다가 어깨로 부딪쳤다면 항상 정상적인 경합일까요?','Is every shoulder challenge legal?'],answer:['아닙니다. 공과의 거리, 팔 사용과 충돌 강도를 함께 봅니다. 부주의하거나 무모한 도전은 반칙입니다.','No. Consider ball distance, arm use and force. Careless or reckless challenges are fouls.'],url:law12},
    {title:['공을 먼저 건드려도 반칙일 수 있어요','Playing the ball first does not excuse a foul'],question:['공을 건드린 뒤 위험하게 상대를 걷어찼다면?','What if a player touches the ball, then dangerously kicks the opponent?'],answer:['공을 먼저 만졌다는 이유만으로 정상 경합이 되지 않습니다. 상대에게 가한 도전의 위험성도 판단합니다.','Touching the ball first is not a defence. Assess the danger of the challenge too.'],url:law12},
    {title:['스로인 ① 발과 손의 기본','Throw-in 1: feet and hands'],question:['공을 놓는 순간 한쪽 발이 완전히 지면에서 떠 있고, 공이 동료에게 갔다면?','One foot is fully off the ground at release and the ball reaches a teammate. Legal?'],answer:['잘못된 스로인으로 상대에게 넘어갑니다. 공을 놓을 때 두 발 각각 일부가 선 위나 선 밖 지면에 닿아야 하며, 양손으로 머리 뒤에서 머리 위를 지나 던집니다.','No: the opponents get the throw-in. At release, part of each foot must touch the line or ground outside it; use both hands from behind and over the head.'],url:law15},
    {title:['핸드볼: 팔에 맞으면 모두 반칙일까?','Handball: is every touch an offence?'],question:['공이 팔에 닿았다는 사실만으로 반칙일까요?','Is touching the arm enough to decide handball?'],answer:['아닙니다. 고의성, 몸을 부자연스럽게 크게 만든 팔 위치 등을 봅니다. 직접·직후 득점에는 별도 기준이 있습니다.','No. Assess deliberate contact and unnatural enlargement of the body. Direct or immediate scoring has separate criteria.'],url:law12},
    {title:['오프사이드 위치와 반칙은 달라요','Offside position is not itself an offence'],question:['오프사이드 위치에 서 있기만 해도 반칙일까요?','Is simply standing in an offside position an offence?'],answer:['아닙니다. 동료가 공을 건드리는 시점의 위치와 이후 플레이·상대 방해 등 관여를 함께 판단합니다.','No. Judge the position when a teammate touches the ball and subsequent involvement, such as playing it or interfering with an opponent.'],url:'https://www.theifab.com/laws/latest/offside/'},
    {title:['공 보호와 상대 진로 방해 구분하기','Shielding versus obstructing an opponent'],question:['공이 발을 뻗어 닿을 수 있는 거리에 있을 때 몸으로 공을 보호해도 될까요?','May a player shield a ball within playing distance?'],answer:['가능하지만 팔이나 몸으로 상대를 붙잡아 막아서는 안 됩니다. 공과 멀리 떨어진 진로 방해와는 구분합니다.','Yes, without holding off the opponent with arms or body. Distinguish this from obstruction away from the ball.'],url:law12},
    {title:['스로인 ② 선을 밟아도 될까?','Throw-in 2: may you stand on the line?'],question:['두 발의 뒤꿈치가 선에 닿아 있고 나머지 동작도 올바르면?','Both heels touch the line and the rest of the throw is correct. Legal?'],answer:['정상입니다. 발 전체가 선 밖에 있을 필요는 없습니다. 상대는 스로인 지점에서 최소 2m 떨어져야 합니다.','Yes. The entire foot need not be outside the line. Opponents must remain at least 2m from the throw-in point.'],url:law15},
    {title:['다시 보기: 심판도 선수도 같은 기준으로','Review: a shared standard for players and referees'],question:['이번 경기에서 헷갈린 장면 하나를 떠올려 보세요. 무엇을 보고 판단해야 할까요?','Recall one unclear incident. What would you need to see before judging it?'],answer:['공의 위치·접촉 방식·위험성을 설명해 보세요. 영상 각도가 부족하면 단정하지 않고, 경기 후 공식 기준으로 함께 복습합니다.','Describe ball position, contact and danger. Avoid certainty from an unclear angle; review the official guidance together afterwards.'],url:law12}
];
export function refereeLessonIndex(date) {
    const time=Date.parse(`${date}T12:00:00Z`), anchor=Date.UTC(2026,8,21,12);
    return Number.isFinite(time)?((Math.floor((time-anchor)/604800000)%8)+8)%8:0;
}
export function refereeLessonHtml(date,lang='ko') {
    const i=refereeLessonIndex(date), item=REFEREE_LESSONS[i], en=lang==='en', k=en?1:0;
    return `<section class="referee-lesson"><p class="coach-eyebrow">${en?'ONE REFEREE MOMENT':'이번 주 판정 한 장면'} · ${i+1}/8</p><h3>${esc(item.title[k])}</h3><p>${esc(item.question[k])}</p><details><summary>${en?'Think first, then reveal the explanation':'먼저 생각해 보고 · 해설 보기'}</summary><p>${esc(item.answer[k])}</p><a class="practice-source" href="${item.url}" target="_blank" rel="noopener noreferrer">${en?'IFAB official law':'IFAB 공식 규칙'} ↗</a></details><p class="coach-note">${en?'Eight topics rotate by match date. No answers or scores are recorded. Short examples do not cover every exception.':'경기 날짜에 따라 8개 주제를 순환합니다. 응답·점수는 저장하지 않습니다. 짧은 예시는 모든 예외 상황을 다루지는 않습니다.'}</p></section>`;
}
